<?php
/**
 * UnderStrap ACF specific
 *
 * @package UnderStrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;


function ar_funding_opps(){
    $html = '';
    if( have_rows('funding_opportunities') ):
        // Loop through rows.
        while( have_rows('funding_opportunities') ) : the_row();
            // Load sub field value.
            $title = get_sub_field('funding_title');
            $text = get_sub_field('funding_description');
            $link = get_sub_field('funding_link');
            $audience = explode(' ', $title)[0];
            // Do something...
            $html .= "<div class='funding-opp'>
                         <div class='funding-details'>
                            {$text}
                            <a class='btn btn-ar btn-blue' href='{$link}' aria-label='Apply for {$title} funding.'>{$title}</a>
                        </div>
                    </div>";
        // End loop.
        endwhile;
        return $html;
        // No value.
        else :
            // Do something...
        endif;

}


//resource to build link button in resources
function ar_go_to_link(){
    global $post;
    $post_id = $post->ID;
    $link = get_field('link');
    $type = get_field('type')->name;
    return "<a class='resource-link btn btn-ar' href='{$link}'>Click to {$type} and Learn</a>";
}


//for people to get the links

function ar_person_links($field){
    $person = get_the_title();
    if(get_field($field)){
        $all = get_field_object($field);
        $label = $all['label'];
        $url = $all['value'];
        $class = $all['name'];
        //var_dump($name);
        return "<div class='col-md-3'><a class='{$class} btn btn-ar btn-blue' href='{$url}' aria-label='{$person} on {$label}.'>{$label}</a></div>";
    }
}


/** add additional classes / id to the facetwp-template div generated by a facetwp 
 ** layout template
 **/
add_filter( 'facetwp_shortcode_html', function( $output, $atts) {
    if ( $atts['template'] = 'example' ) { // replace 'example' with name of your template
    /** modify replacement as needed, make sure you keep the facetwp-template class **/
        $output = str_replace( 'class="facetwp-template"', 'class="facetwp-template row"', $output );
    }
    return $output; 
}, 10, 2 );


    //save acf json
        add_filter('acf/settings/save_json', 'acf_special_json_save_point');
         
        function acf_special_json_save_point( $path ) {
            
            // update path
            $path = get_stylesheet_directory() . '/acf-json'; //replace w get_stylesheet_directory() for theme
            
            
            // return
            return $path;
            
        }


        // load acf json
        add_filter('acf/settings/load_json', 'acf_special_json_load_point');

        function acf_special_json_load_point( $paths ) {
            
            // remove original path (optional)
            unset($paths[0]);
            
            
            // append path
            $paths[] = get_stylesheet_directory()  . '/acf-json';//replace w get_stylesheet_directory() for theme
            
            
            // return
            return $paths;
            
        }

/* populate front end form for groups to be group */
// add_filter('acf/prepare_field/key=field_61a8de4f52301', 'ar_populate_form_type');
// function ar_populate_form_type($field) {
//     global $template;
//    $page_template = basename($template);
//   // only on front end
//   if (is_admin()) {
//     return $field;
//   }
//   if($page_template == 'submit-group.php'){
//     $field['value'] = 'Organization';
//   }
  
//   return $field;
//}

function people_related_image($class){
    global $post;
    if(has_post_thumbnail($post->ID)){
        return get_the_post_thumbnail( $post->ID, 'medium', $class );
    } else {
        return file_get_contents(locate_template("imgs/inline-tri-svg.php"));
       //return get_template_part( 'imgs/inline', 'tri-svg' );
    } 
}


